[general]
import = ["~/.config/alacritty/themes/current.toml"]

[window]
padding = { x = 4, y = 4 }
opacity = 0.9

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

size = 10.0

